datasets:
  # train_path: ./data/kcbert_joint/datasets/joint_20221104_17_37/joint_train.json
  # valid_path: ./data/kcbert_joint/datasets/joint_20221104_17_37/joint_val.json
  # test_path: ./data/kcbert_joint/datasets/joint_20221104_17_37/joint_test.json
  
  train_path: ./data/kcbert_joint/datasets/joint_20221118_all/joint_train.json
  valid_path: ./data/kcbert_joint/datasets/joint_20221118_all/joint_val.json
  test_path: ./data/kcbert_joint/datasets/joint_20221118_all/joint_test.json

  types_path: ./data/kcbert_joint/datasets/types.json

model:
  model_type: joint_multi_instance
  encoder_path: 'beomi/kcbert-base'
  tokenizer_path: 'beomi/kcbert-base'
  mention_threshold: 0.85
  coref_threshold: 0.85
  rel_threshold: 0.6
  meta_embedding_size: 25
  prop_drop: 0.1
  # max_position_embeddings: 2000

sampling:
  neg_mention_count: 200
  neg_coref_count: 200
  neg_relation_count: 200
  max_span_size: 10
  sampling_processes: 8

loss:
  entity_weight: 0.25
  relation_weight: 1

training:
  batch_size: 1
  min_epochs: 1000
  max_epochs: 1000
  lr: 5e-5
  lr_warmup: 0.1
  weight_decay: 0.01
  max_grad_norm: 1.0

inference:
  valid_batch_size: 1
  test_batch_size: 1

distribution:
  gpus: [0]
  accelerator: ''
  prepare_data_per_node: false

misc:
  store_predictions: true
  store_examples: true
  final_valid_evaluate: true

hydra:
  run:
    dir: ./data/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: run_config