### main
data_path: "/home/xaiplanet/xai_workspace/nlp_integrate/Sample_Data"

### 원본 -> .txt -> 요약 파일 저장 
save_path: "/home/xaiplanet/xai_workspace/nlp_integrate/out_puts"


### 원본 -> .txt 로 변환 된 파일 저장
save_path_plumber: "/home/xaiplanet/xai_workspace/nlp_integrate/SampleData"

exceptions:  ['㎉', '㎘', '㎢', ';', '〉', '〕', '⇒', '》', '℉', '÷', '％', '+', '㎖', '｜', '½', '㎧', '&', '<', '>', '(', ')', ':', '：', '」', '』', '‧', '․', 'ｍ', '㎡', '×', '㎏', '$', '“', '·', '㎜', '"', '”', 
'①', '②', '‘', '’', ',', "'", '㎞', '㎸', '℃', '%', '~', '…', '?', '[', ']', '=', '/', '.', '∼', '-', '㎥', '@', '～', 'ℓ', '㎝', '→', '', '】', '/', '㎠', '㎛', 'Ⅲ', 'Ⅱ','○','◯','³']

symbol: ['가.', '나.', '라.', '마.', '바.', '사.', '아.', '자.', '- ', ' <','o ']


### keyword
font_path: "/home/xaiplanet/xai_workspace/nlp_integrate/Noto_Sans_KR/NotoSansKR-Medium.otf"